/* ==========================================================
   Frases de la versión de Tiff — firmadas por NR.
   Edítalas libremente: una frase por línea, entre comillas.
   Cambian solas cada día (y no se repiten hasta dar la vuelta).
   ========================================================== */

const FRASES_MOTIVACION = [
  // constancia
  "No tiene que ser perfecto, tiene que ser constante.",
  "Un buen día no te cambia. Muchos días normales bien hechos, sí.",
  "La disciplina es acordarte de lo que quieres cuando no tienes ganas.",
  "Hoy solo te toca hacer lo de hoy.",
  "Pequeños pasos, todos los días. Así se llega lejos.",
  "No cuentes los días, haz que los días cuenten.",
  "Lo que haces seguido pesa más que lo que haces a veces.",
  "Si fallas una comida, la siguiente es tu nueva oportunidad.",
  "No se trata de empezar el lunes. Se trata de seguir hoy.",
  "Cada registro es un voto por la persona que quieres ser.",
  "Tu futuro se está construyendo con lo que decides hoy.",
  "Ir lento también es avanzar.",
  "Constancia le gana a intensidad, siempre.",
  "No necesitas motivación todos los días, necesitas hábitos.",
  "Lo difícil se vuelve normal si lo repites.",
  "Un día a la vez. Una comida a la vez.",
  "El progreso se esconde en los días aburridos.",
  "La meta no es un sprint, es un camino que disfrutas.",
  "Lo estás haciendo mejor de lo que crees.",
  "Mañana vas a agradecer lo que hiciste hoy.",
  "Cumplir contigo misma también es una forma de amor propio.",
  "El hábito que construyes hoy te sostiene mañana.",
  "No pares porque va lento. Para nada.",
  "Lo que no se mide no se mejora, y tú lo estás midiendo.",
  "Una mala comida no arruina un buen día.",
  "Un mal día no arruina una buena semana.",
  "Registrar lo que comes es darte información, no juzgarte.",
  "La constancia se construye con días imperfectos.",
  "No busques el día perfecto para empezar. Hoy es suficiente.",
  "Tu mejor versión no aparece de golpe, se entrena.",
  // comida
  "Come para nutrirte, no para castigarte.",
  "Tu plato de hoy es una inversión en tu energía de mañana.",
  "Proteína primero, lo demás se acomoda.",
  "El agua también es parte del plan.",
  "Comer bien es cuidarte, no hacer dieta.",
  "Ningún alimento es bueno o malo; es cuestión de cantidades.",
  "Pesar tu comida es darle a tu esfuerzo la precisión que merece.",
  "Las verduras nunca sobran en el plato.",
  "Comer despacio también es comer bien.",
  "Llena tu plato de colores.",
  "Planear tu comida es la mitad del trabajo.",
  "Un antojo no es una orden.",
  "Puedes disfrutar la comida y cuidar tu meta al mismo tiempo.",
  "Escoge lo que te hace sentir bien después, no solo durante.",
  "Tu cuerpo agradece la comida de verdad.",
  "Tener hambre de verdad y tener ganas de comer no son lo mismo.",
  "Balance no es perfección, es equilibrio.",
  "Deja espacio para lo que disfrutas; eso también es sostenible.",
  "Cocinar en casa es una forma de quererte.",
  "Cada comida es una nueva oportunidad de elegir bien.",
  "Nutrirte bien es el mejor regalo diario para tu cuerpo.",
  "Come con intención, no con distracción.",
  "Menos procesado, más real.",
  "La fruta también es postre.",
  "Hidrátate antes de decidir si tienes hambre.",
  "El desayuno de campeona no tiene que ser complicado.",
  "Un plato bien armado te deja satisfecha y con energía.",
  "La comida es combustible y también es placer. Las dos cosas caben.",
  "Tu meta de proteína te ayuda a sentirte llena y fuerte.",
  "Cuida las porciones, no te prohíbas nada.",
  // cuerpo y ejercicio
  "Muévete porque quieres a tu cuerpo, no porque lo odias.",
  "Una caminata también cuenta.",
  "Tu cuerpo puede más de lo que tu mente cree.",
  "Sudar hoy es sonreír mañana.",
  "El mejor ejercicio es el que sí vas a hacer.",
  "Diez minutos de movimiento le ganan a cero.",
  "Fuerte no es un tamaño, es una actitud.",
  "Cada repetición cuenta.",
  "El cansancio de entrenar se siente mejor que el arrepentimiento de no hacerlo.",
  "Estírate, respira, sigue.",
  "Tu cuerpo te escucha; háblale bonito.",
  "Entrena para sentirte bien, no solo para verte bien.",
  "Subir escaleras también es entrenar.",
  "No compitas con nadie más que con la de ayer.",
  "Hoy muévete un poco más que ayer.",
  "Tu cuerpo es tu casa; cuídalo como tal.",
  "Mover el cuerpo también limpia la mente.",
  "Aunque sea poquito, hazlo.",
  "Tus piernas pueden más. Tu mente también.",
  "El sudor es tu esfuerzo saliendo a saludar.",
  // descanso y bienestar
  "Dormir bien también es parte del progreso.",
  "Descansar no es rendirse, es recargar.",
  "Escucha a tu cuerpo: a veces pide movimiento, a veces pide pausa.",
  "El estrés también pesa; respira hondo.",
  "Tu salud mental importa tanto como tu meta.",
  "Un día de descanso también es parte del plan.",
  "Apaga la pantalla, duerme temprano, gana mañana.",
  "Tomar agua es el hábito más fácil de ganar hoy.",
  "Cuídate como cuidarías a alguien que amas.",
  "La paciencia también es una fortaleza.",
  "Respira. Lo estás haciendo bien.",
  "Tu energía de hoy depende de cómo dormiste anoche.",
  "Date permiso de descansar sin culpa.",
  "Un cuerpo descansado toma mejores decisiones.",
  "Bajar el ritmo no es retroceder.",
  // mentalidad
  "Cree en ti aunque la báscula no coopere hoy.",
  "La báscula mide peso, no tu valor.",
  "Tu progreso no siempre se ve en números.",
  "Compárate solo con la versión de ti de hace un mes.",
  "La motivación te arranca; el hábito te mantiene.",
  "Eres más fuerte que cualquier antojo.",
  "Háblate como le hablarías a tu mejor amiga.",
  "Tus metas merecen tu esfuerzo.",
  "Dudar es normal. Rendirse es opcional.",
  "Lo que hoy te cuesta, mañana te sale solo.",
  "El cambio empieza en la cabeza y termina en el espejo.",
  "No es suerte, es trabajo de todos los días.",
  "Tu actitud decide la mitad del resultado.",
  "Confía en el proceso, aunque no veas el final.",
  "Cada decisión cuenta, hasta las pequeñas.",
  "La versión de ti que quieres ser ya empezó a existir.",
  "No te enfoques en lo que falta, celebra lo que llevas.",
  "Tú puedes con días difíciles; ya lo has demostrado.",
  "Ser amable contigo también es parte del plan.",
  "El miedo a fallar no debe ganarle a tus ganas de intentarlo.",
  "Paso a paso, pero sin parar.",
  "Si fuera fácil, no sería tan bonito lograrlo.",
  "Tu esfuerzo de hoy es la sonrisa de mañana.",
  "No hace falta que alguien crea en ti si tú crees.",
  "Recuerda por qué empezaste.",
  "Una mente tranquila come mejor.",
  "La culpa no quema calorías; seguir adelante sí ayuda.",
  "Todo lo que vale la pena toma tiempo.",
  "Tú decides cómo termina el día.",
  "Tu cuerpo no es un proyecto; es tu compañero.",
  "Vas a lograrlo porque ya decidiste intentarlo.",
  "El progreso lento sigue siendo progreso.",
  "Que nadie apague tus ganas, ni siquiera tú.",
  "Enfócate en lo que puedes controlar hoy.",
  "Nadie ve tu esfuerzo diario, pero tu cuerpo sí lo nota.",
  "Una decisión saludable lleva a la siguiente.",
  "Sé paciente contigo; estás aprendiendo.",
  "Estás construyendo algo que dura.",
  "Hacer las cosas bien se siente bien.",
  "Los resultados llegan a quien no se detiene.",
  // progreso y logros
  "Mira hasta dónde has llegado.",
  "Cada semana registrada es una semana ganada.",
  "Celebra cada pequeño logro.",
  "Tu ropa, tu energía y tu ánimo también son resultados.",
  "Hoy eres más constante que ayer.",
  "Lo que antes era difícil hoy ya es costumbre.",
  "Tu racha es prueba de tu compromiso.",
  "Ya no estás empezando; estás avanzando.",
  "La meta está más cerca de lo que parece.",
  "Estás escribiendo tu propia historia de éxito.",
  "El progreso real es el que puedes sostener.",
  "Tu esfuerzo ya se nota, aunque tú todavía no lo veas.",
  "Un gramo a la vez también suma.",
  "Hoy diste un paso más hacia tu meta.",
  "Ya lo estás logrando.",
  "Nadie te regaló esto; te lo estás ganando.",
  "Cada día registrado es una victoria silenciosa.",
  "Tu constancia inspira más de lo que crees.",
  "Vas por buen camino.",
  "Lo mejor está por venir.",
  // días difíciles
  "Si hoy fue difícil, mañana empieza limpio.",
  "Un tropiezo no borra tu camino.",
  "Está bien no tener un día perfecto.",
  "Cuando no puedas correr, camina. Pero no te detengas.",
  "Hoy toca ser suave contigo.",
  "Los días malos también pasan.",
  "No te rindas en un mal día; descansa y sigue.",
  "Volver a empezar también es valiente.",
  "No hace falta hacerlo todo; basta con no dejarlo.",
  "Sé tu propia porra hoy.",
  "Un día libre no es un fracaso.",
  "Lo importante es lo que haces después de fallar.",
  "El camino tiene curvas, y está bien.",
  "No te castigues; ajusta y sigue.",
  "Tu valor no depende de lo que comiste hoy.",
  "Mañana es otra página.",
  "La perfección no existe; la constancia sí.",
  "Puedes empezar de nuevo las veces que haga falta.",
  "Incluso en los días lentos, sigues siendo increíble.",
  "Lo que importa es no soltar.",
  // energía del día
  "Hoy es un gran día para cuidarte.",
  "Buenos días, campeona. Vamos por todo.",
  "Arranca el día con agua y buena actitud.",
  "Que tu primera comida del día sea una buena decisión.",
  "Hoy vas a brillar.",
  "Dale a tu día la energía que mereces.",
  "Hoy el plan es sencillo: comer bien y sentirte bien.",
  "Sonríe, te ves mejor cuando te cuidas.",
  "Tú mandas en tu día.",
  "Haz que hoy cuente.",
  "Hoy tu única competencia eres tú.",
  "Levántate con ganas; la meta te espera.",
  "Hoy es un buen día para sentirte orgullosa.",
  "Pon música, muévete, sonríe.",
  "Cierra el día sabiendo que diste lo mejor.",
  "Un buen día empieza con una buena decisión.",
  "Llena tu día de cosas que te hagan bien.",
  "Tu energía es contagiosa, úsala bien.",
  "Termina el día más fuerte de lo que empezaste.",
  "Hoy también vas a poder.",
  "Tu constancia de hoy es tu confianza de mañana.",
  "Elige lo que te acerca a tu meta, aunque sea poquito.",
  "Lo que siembras en tu cuerpo, lo cosechas en tu energía.",
  "Hoy no se negocia contigo misma: se cumple.",
  "Eres capaz de cosas grandes, empezando por las pequeñas.",
];

const FRASES_AMOR = [
  "Te amo en todas tus versiones, y me encanta verte crecer.",
  "Estoy orgulloso de ti, Glori. Hoy y siempre.",
  "Eres lo más bonito de mis días, amorcito.",
  "Cada vez que te cuidas, me enamoro más de ti.",
  "Gracias por ser mi compañera en todo, baby.",
  "Ya eres perfecta para mí; esto es para que te sientas increíble tú.",
  "Me haces feliz de maneras que no sé explicar.",
  "Contigo todo es mejor, Glorita.",
  "Eres mi lugar favorito.",
  "Te admiro más de lo que te digo.",
  "Tu sonrisa me arregla el día, Glori.",
  "Siempre voy a estar de tu lado.",
  "No hay meta que no puedas lograr, y yo voy a estar ahí para verlo.",
  "Me encanta la mujer fuerte que eres.",
  "Eres mi persona.",
  "Si hoy te cuesta, bebé, recuerda que yo creo en ti.",
  "Te elegiría todos los días.",
  "Eres mi motivación también.",
  "Tu esfuerzo me inspira.",
  "Qué suerte tengo de tenerte, amorchi.",
  "Eres hermosa por dentro y por fuera.",
  "Me encanta hacer equipo contigo.",
  "Todo lo que te propones lo logras, Glori. Esto también.",
  "Te amo más que ayer y menos que mañana.",
  "Gracias por hacer mi vida más bonita.",
  "Cuidarte es cuidar a la persona que más amo.",
  "Eres mi paz, amorcito.",
  "Me encanta verte feliz, baby.",
  "Tú haces que cualquier día sea especial.",
  "Nunca olvides lo valiosa que eres, Glorita.",
  "Contigo quiero todos los mañanas.",
  "Eres mi orgullo, baby.",
  "No importa el número de la báscula: te amo igual.",
  "Eres la mejor decisión de mi vida.",
  "Tu fuerza me enamora, bebé.",
  "Me gusta todo de ti, hasta lo que tú no ves.",
  "Estoy aquí para ti, amorchi. Siempre.",
  "Juntos podemos con todo.",
  "Eres mi compañera favorita de aventuras.",
  "Tus logros son mis alegrías.",
  "Cada día contigo es un regalo.",
  "Tu felicidad es mi prioridad.",
  "Me encanta cómo te brillan los ojos cuando logras algo.",
  "Eres más fuerte de lo que crees, y más amada de lo que imaginas.",
  "Mi corazón es tuyo, Glori.",
  "Gracias por tu paciencia, tu amor y tu risa.",
  "Eres la razón de muchas de mis sonrisas.",
  "Eres lo mejor que me ha pasado.",
  "Contigo aprendí lo que es querer de verdad.",
  "Tú puedes, baby, y yo te echo porras desde aquí.",
  "Hoy también pienso en ti, amorcito.",
  "Ojalá te vieras con mis ojos, Glorita.",
  "Eres mi casa.",
  "Te quiero sana, feliz y conmigo mucho tiempo.",
  "Me enamora tu disciplina.",
  "Eres increíble, Glorita. No lo olvides.",
  "Qué bonito es crecer a tu lado.",
  "Tu esfuerzo no pasa desapercibido para mí.",
  "Gracias por dejarme acompañarte en esto.",
  "Te amo por quien eres, no por cómo te ves.",
  "Eres mi sol en los días nublados.",
  "Me haces querer ser mejor cada día.",
  "Contigo hasta lo simple es especial.",
  "Eres mi favorita, Glori. Siempre.",
  "Tu bienestar es mi alegría.",
  "Juntos, a cuidarnos y a querernos.",
  "Me encanta nuestra vida juntos.",
  "Eres mi mejor amiga y mi amor.",
  "Brillas sin intentarlo.",
  "Estás haciendo algo bonito por ti, y eso me hace feliz.",
  "Te amo con todo lo que soy, bebé.",
  "Me inspira ver cómo nunca te rindes.",
  "Eres suficiente, siempre lo has sido.",
  "Contigo el tiempo vuela.",
  "Tu risa es mi sonido favorito, amorchi.",
  "Eres mi equipo.",
  "Qué orgullo decir que eres mía, y yo tuyo.",
  "Hoy te mando un abrazo en forma de frase, baby.",
  "Nunca dejes de creer en ti; yo nunca lo haré.",
  "Eres mi hogar, donde sea que estemos.",
  "Me encanta tu forma de ver la vida.",
  "Me haces sentir afortunado todos los días.",
  "Tú haces que todo valga la pena.",
  "Gracias por existir, Glorita.",
  "Eres mi inspiración favorita.",
  "Cuando te miro, sé que elegí bien.",
  "Te veo, te valoro y te amo.",
  "Eres mi alegría diaria, amorcito.",
  "Siempre serás mi prioridad.",
  "Tu corazón es lo más bonito que tienes.",
  "Contigo quiero celebrar cada meta.",
  "Me encanta que te estés cuidando, amorcito. Te lo mereces.",
  "Eres mi mejor historia.",
  "Te amo hoy, mañana y todos los días, Glori.",
  "Mi admiración por ti crece cada día.",
  "Eres fuerte, bella y mía.",
  "Nada me hace más feliz que verte bien, bebé.",
  "Tú y yo, siempre, amorchi.",
  "Gracias por hacer de cada día algo especial.",
  "Te amo, Glori.",
];

/* Versículos cortos — Reina-Valera 1960. [texto, cita] */
const FRASES_VERSICULOS = [
  ["Todo lo puedo en Cristo que me fortalece.", "Filipenses 4:13"],
  ["Fuerza y honor son su vestidura; y se ríe de lo por venir.", "Proverbios 31:25"],
  ["Dios está en medio de ella; no será conmovida.", "Salmos 46:5"],
  ["Jehová es mi pastor; nada me faltará.", "Salmos 23:1"],
  ["Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.", "Mateo 6:33"],
  ["Encomienda a Jehová tu camino, y confía en él; y él hará.", "Salmos 37:5"],
  ["Deléitate asimismo en Jehová, y él te concederá las peticiones de tu corazón.", "Salmos 37:4"],
  ["Este es el día que hizo Jehová; nos gozaremos y alegraremos en él.", "Salmos 118:24"],
  ["Echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros.", "1 Pedro 5:7"],
  ["Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.", "Mateo 11:28"],
  ["El amor es sufrido, es benigno.", "1 Corintios 13:4"],
  ["Y ahora permanecen la fe, la esperanza y el amor, estos tres; pero el mayor de ellos es el amor.", "1 Corintios 13:13"],
  ["Fíate de Jehová de todo tu corazón, y no te apoyes en tu propia prudencia.", "Proverbios 3:5"],
  ["Reconócelo en todos tus caminos, y él enderezará tus veredas.", "Proverbios 3:6"],
  ["Lámpara es a mis pies tu palabra, y lumbrera a mi camino.", "Salmos 119:105"],
  ["Jehová es mi luz y mi salvación; ¿de quién temeré?", "Salmos 27:1"],
  ["Estad quietos, y conoced que yo soy Dios.", "Salmos 46:10"],
  ["Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.", "Salmos 46:1"],
  ["Clama a mí, y yo te responderé.", "Jeremías 33:3"],
  ["Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz, y no de mal, para daros el fin que esperáis.", "Jeremías 29:11"],
  ["No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo.", "Isaías 41:10"],
  ["Pero los que esperan a Jehová tendrán nuevas fuerzas; levantarán alas como las águilas.", "Isaías 40:31"],
  ["Correrán, y no se cansarán; caminarán, y no se fatigarán.", "Isaías 40:31"],
  ["Él da esfuerzo al cansado, y multiplica las fuerzas al que no tiene ningunas.", "Isaías 40:29"],
  ["Te alabaré; porque formidables, maravillosas son tus obras.", "Salmos 139:14"],
  ["Toda tú eres hermosa, amiga mía, y en ti no hay mancha.", "Cantares 4:7"],
  ["Yo soy de mi amado, y mi amado es mío.", "Cantares 6:3"],
  ["Las muchas aguas no podrán apagar el amor, ni lo ahogarán los ríos.", "Cantares 8:7"],
  ["Ponme como un sello sobre tu corazón.", "Cantares 8:6"],
  ["Mejores son dos que uno.", "Eclesiastés 4:9"],
  ["Cordón de tres dobleces no se rompe pronto.", "Eclesiastés 4:12"],
  ["Todo tiene su tiempo, y todo lo que se quiere debajo del cielo tiene su hora.", "Eclesiastés 3:1"],
  ["El corazón alegre hermosea el rostro.", "Proverbios 15:13"],
  ["El corazón alegre constituye buen remedio.", "Proverbios 17:22"],
  ["Sobre toda cosa guardada, guarda tu corazón; porque de él mana la vida.", "Proverbios 4:23"],
  ["Engañosa es la gracia, y vana la hermosura; la mujer que teme a Jehová, esa será alabada.", "Proverbios 31:30"],
  ["Mujer virtuosa, ¿quién la hallará? Porque su estima sobrepasa largamente a la de las piedras preciosas.", "Proverbios 31:10"],
  ["Ciñe de fuerza sus lomos, y esfuerza sus brazos.", "Proverbios 31:17"],
  ["Abre su boca con sabiduría, y la ley de clemencia está en su lengua.", "Proverbios 31:26"],
  ["¿O ignoráis que vuestro cuerpo es templo del Espíritu Santo, el cual está en vosotros?", "1 Corintios 6:19"],
  ["Glorificad, pues, a Dios en vuestro cuerpo y en vuestro espíritu, los cuales son de Dios.", "1 Corintios 6:20"],
  ["Si, pues, coméis o bebéis, o hacéis otra cosa, hacedlo todo para la gloria de Dios.", "1 Corintios 10:31"],
  ["Y todo lo que hacéis, hacedlo de corazón, como para el Señor y no para los hombres.", "Colosenses 3:23"],
  ["No nos cansemos, pues, de hacer bien; porque a su tiempo segaremos, si no desmayamos.", "Gálatas 6:9"],
  ["Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre, templanza.", "Gálatas 5:22-23"],
  ["Porque no nos ha dado Dios espíritu de cobardía, sino de poder, de amor y de dominio propio.", "2 Timoteo 1:7"],
  ["El que comenzó en vosotros la buena obra, la perfeccionará.", "Filipenses 1:6"],
  ["Por nada estéis afanosos.", "Filipenses 4:6"],
  ["Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones.", "Filipenses 4:7"],
  ["Regocijaos en el Señor siempre. Otra vez digo: ¡Regocijaos!", "Filipenses 4:4"],
  ["Prosigo a la meta, al premio del supremo llamamiento de Dios en Cristo Jesús.", "Filipenses 3:14"],
  ["Olvidando ciertamente lo que queda atrás, y extendiéndome a lo que está delante.", "Filipenses 3:13"],
  ["Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien.", "Romanos 8:28"],
  ["Si Dios es por nosotros, ¿quién contra nosotros?", "Romanos 8:31"],
  ["Gozosos en la esperanza; sufridos en la tribulación; constantes en la oración.", "Romanos 12:12"],
  ["No seas vencido de lo malo, sino vence con el bien el mal.", "Romanos 12:21"],
  ["Y el Dios de esperanza os llene de todo gozo y paz en el creer.", "Romanos 15:13"],
  ["El gozo de Jehová es vuestra fuerza.", "Nehemías 8:10"],
  ["Mira que te mando que te esfuerces y seas valiente; no temas ni desmayes.", "Josué 1:9"],
  ["Jehová te bendiga, y te guarde.", "Números 6:24"],
  ["Jehová haga resplandecer su rostro sobre ti, y tenga de ti misericordia.", "Números 6:25"],
  ["Nuevas son cada mañana; grande es tu fidelidad.", "Lamentaciones 3:23"],
  ["Por la misericordia de Jehová no hemos sido consumidos, porque nunca decayeron sus misericordias.", "Lamentaciones 3:22"],
  ["Crea en mí, oh Dios, un corazón limpio, y renueva un espíritu recto dentro de mí.", "Salmos 51:10"],
  ["Bendice, alma mía, a Jehová, y no olvides ninguno de sus beneficios.", "Salmos 103:2"],
  ["Alzaré mis ojos a los montes; ¿de dónde vendrá mi socorro? Mi socorro viene de Jehová.", "Salmos 121:1-2"],
  ["Jehová guardará tu salida y tu entrada desde ahora y para siempre.", "Salmos 121:8"],
  ["En paz me acostaré, y asimismo dormiré; porque solo tú, Jehová, me haces vivir confiado.", "Salmos 4:8"],
  ["Gustad, y ved que es bueno Jehová.", "Salmos 34:8"],
  ["Cercano está Jehová a los quebrantados de corazón.", "Salmos 34:18"],
  ["El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.", "Salmos 91:1"],
  ["Enséñanos de tal modo a contar nuestros días, que traigamos al corazón sabiduría.", "Salmos 90:12"],
  ["Sea la luz de Jehová nuestro Dios sobre nosotros.", "Salmos 90:17"],
  ["Él sana a los quebrantados de corazón, y venda sus heridas.", "Salmos 147:3"],
  ["Todo lo que respira alabe a JAH. Aleluya.", "Salmos 150:6"],
  ["En tu presencia hay plenitud de gozo; delicias a tu diestra para siempre.", "Salmos 16:11"],
  ["Por la noche durará el lloro, y a la mañana vendrá la alegría.", "Salmos 30:5"],
  ["Echa sobre Jehová tu carga, y él te sustentará.", "Salmos 55:22"],
  ["En el día que temo, yo en ti confío.", "Salmos 56:3"],
  ["Amado, yo deseo que tú seas prosperado en todas las cosas, y que tengas salud, así como prospera tu alma.", "3 Juan 1:2"],
  ["En el amor no hay temor, sino que el perfecto amor echa fuera el temor.", "1 Juan 4:18"],
  ["Nosotros le amamos a él, porque él nos amó primero.", "1 Juan 4:19"],
  ["Dios es amor.", "1 Juan 4:8"],
  ["La paz os dejo, mi paz os doy.", "Juan 14:27"],
  ["No se turbe vuestro corazón, ni tenga miedo.", "Juan 14:27"],
  ["Nada hay imposible para Dios.", "Lucas 1:37"],
  ["Pedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá.", "Mateo 7:7"],
  ["Vosotros sois la luz del mundo.", "Mateo 5:14"],
  ["Así que, no os afanéis por el día de mañana.", "Mateo 6:34"],
  ["He aquí yo estoy con vosotros todos los días, hasta el fin del mundo.", "Mateo 28:20"],
  ["Bástate mi gracia; porque mi poder se perfecciona en la debilidad.", "2 Corintios 12:9"],
  ["Si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron; he aquí todas son hechas nuevas.", "2 Corintios 5:17"],
  ["Porque por fe andamos, no por vista.", "2 Corintios 5:7"],
  ["Y sobre todas estas cosas vestíos de amor, que es el vínculo perfecto.", "Colosenses 3:14"],
  ["Estad siempre gozosos. Orad sin cesar. Dad gracias en todo.", "1 Tesalonicenses 5:16-18"],
  ["Levántate, resplandece; porque ha venido tu luz.", "Isaías 60:1"],
  ["He aquí que yo hago cosa nueva; pronto saldrá a luz.", "Isaías 43:19"],
  ["Jehová peleará por vosotros, y vosotros estaréis tranquilos.", "Éxodo 14:14"],
  ["Jehová está en medio de ti, poderoso, él salvará; se gozará sobre ti con alegría, callará de amor.", "Sofonías 3:17"],
  ["Corramos con paciencia la carrera que tenemos por delante.", "Hebreos 12:1"],
];

/* ==========================================================
   ENGLISH — same order as the Spanish lists (same phrase each day in both languages).
   Verses: King James Version (KJV).
   ========================================================== */
const FRASES_MOTIVACION_EN = [
  "It doesn't have to be perfect, it has to be consistent.",
  "One good day won't change you. Many ordinary days done right will.",
  "Discipline is remembering what you want when you don't feel like it.",
  "Today you only have to do today.",
  "Small steps, every day. That's how you go far.",
  "Don't count the days, make the days count.",
  "What you do often matters more than what you do once in a while.",
  "If you miss one meal, the next one is your new chance.",
  "It's not about starting Monday. It's about keeping going today.",
  "Every entry is a vote for the person you want to be.",
  "Your future is being built by what you decide today.",
  "Going slow is still moving forward.",
  "Consistency beats intensity, always.",
  "You don't need motivation every day, you need habits.",
  "Hard things become normal when you repeat them.",
  "One day at a time. One meal at a time.",
  "Progress hides in the boring days.",
  "The goal isn't a sprint, it's a path you enjoy.",
  "You're doing better than you think.",
  "Tomorrow you'll thank yourself for what you did today.",
  "Keeping promises to yourself is a form of self-love too.",
  "The habit you build today holds you up tomorrow.",
  "Don't stop because it's slow. Not at all.",
  "What isn't measured doesn't improve, and you're measuring it.",
  "One bad meal doesn't ruin a good day.",
  "One bad day doesn't ruin a good week.",
  "Logging what you eat is giving yourself information, not judging yourself.",
  "Consistency is built on imperfect days.",
  "Don't wait for the perfect day to start. Today is enough.",
  "Your best self doesn't show up all at once; it's trained.",
  "Eat to nourish yourself, not to punish yourself.",
  "Today's plate is an investment in tomorrow's energy.",
  "Protein first, the rest falls into place.",
  "Water is part of the plan too.",
  "Eating well is taking care of yourself, not dieting.",
  "No food is good or bad; it's all about amounts.",
  "Weighing your food gives your effort the precision it deserves.",
  "There's never too many veggies on the plate.",
  "Eating slowly is eating well too.",
  "Fill your plate with color.",
  "Planning your meals is half the work.",
  "A craving is not an order.",
  "You can enjoy food and take care of your goal at the same time.",
  "Choose what makes you feel good after, not just during.",
  "Your body is grateful for real food.",
  "Being truly hungry and wanting to eat are not the same.",
  "Balance isn't perfection, it's equilibrium.",
  "Leave room for what you enjoy; that's sustainable too.",
  "Cooking at home is a way of loving yourself.",
  "Every meal is a new chance to choose well.",
  "Nourishing yourself well is the best daily gift for your body.",
  "Eat with intention, not distraction.",
  "Less processed, more real.",
  "Fruit is dessert too.",
  "Drink water before deciding if you're hungry.",
  "A champion's breakfast doesn't have to be complicated.",
  "A well-built plate leaves you satisfied and energized.",
  "Food is fuel and it's also pleasure. There's room for both.",
  "Your protein goal helps you feel full and strong.",
  "Watch your portions, don't forbid yourself anything.",
  "Move because you love your body, not because you hate it.",
  "A walk counts too.",
  "Your body can do more than your mind believes.",
  "Sweat today, smile tomorrow.",
  "The best workout is the one you'll actually do.",
  "Ten minutes of movement beats zero.",
  "Strong isn't a size, it's an attitude.",
  "Every rep counts.",
  "Being tired from training feels better than regretting skipping it.",
  "Stretch, breathe, keep going.",
  "Your body is listening; speak kindly to it.",
  "Train to feel good, not just to look good.",
  "Taking the stairs is training too.",
  "Don't compete with anyone but yesterday's you.",
  "Move a little more today than yesterday.",
  "Your body is your home; take care of it like one.",
  "Moving your body clears your mind too.",
  "Even if it's just a little, do it.",
  "Your legs can do more. So can your mind.",
  "Sweat is your effort coming out to say hi.",
  "Sleeping well is part of progress too.",
  "Resting isn't giving up, it's recharging.",
  "Listen to your body: sometimes it asks for movement, sometimes for a pause.",
  "Stress weighs on you too; breathe deeply.",
  "Your mental health matters as much as your goal.",
  "A rest day is part of the plan too.",
  "Turn off the screen, sleep early, win tomorrow.",
  "Drinking water is the easiest habit to win today.",
  "Take care of yourself like you'd take care of someone you love.",
  "Patience is a strength too.",
  "Breathe. You're doing great.",
  "Today's energy depends on how you slept last night.",
  "Give yourself permission to rest without guilt.",
  "A rested body makes better decisions.",
  "Slowing down isn't going backwards.",
  "Believe in yourself even if the scale won't cooperate today.",
  "The scale measures weight, not your worth.",
  "Your progress doesn't always show in numbers.",
  "Only compare yourself to who you were a month ago.",
  "Motivation gets you started; habit keeps you going.",
  "You're stronger than any craving.",
  "Talk to yourself like you'd talk to your best friend.",
  "Your goals deserve your effort.",
  "Doubting is normal. Giving up is optional.",
  "What's hard today will come naturally tomorrow.",
  "Change starts in your head and ends in the mirror.",
  "It's not luck, it's everyday work.",
  "Your attitude decides half the result.",
  "Trust the process, even if you can't see the end.",
  "Every decision counts, even the small ones.",
  "The version of you that you want to be has already started to exist.",
  "Don't focus on what's missing, celebrate what you've done.",
  "You can handle hard days; you've already proven it.",
  "Being kind to yourself is part of the plan too.",
  "Don't let the fear of failing beat your desire to try.",
  "Step by step, but without stopping.",
  "If it were easy, achieving it wouldn't feel this good.",
  "Today's effort is tomorrow's smile.",
  "You don't need anyone to believe in you if you do.",
  "Remember why you started.",
  "A calm mind eats better.",
  "Guilt doesn't burn calories; moving forward does help.",
  "Everything worth it takes time.",
  "You decide how the day ends.",
  "Your body isn't a project; it's your partner.",
  "You'll make it because you already decided to try.",
  "Slow progress is still progress.",
  "Don't let anyone dim your drive, not even you.",
  "Focus on what you can control today.",
  "No one sees your daily effort, but your body notices.",
  "One healthy decision leads to the next.",
  "Be patient with yourself; you're learning.",
  "You're building something that lasts.",
  "Doing things right feels right.",
  "Results come to those who don't stop.",
  "Look how far you've come.",
  "Every week logged is a week won.",
  "Celebrate every small win.",
  "Your clothes, your energy and your mood are results too.",
  "Today you're more consistent than yesterday.",
  "What used to be hard is now a habit.",
  "Your streak is proof of your commitment.",
  "You're not starting anymore; you're moving forward.",
  "The goal is closer than it looks.",
  "You're writing your own success story.",
  "Real progress is the kind you can sustain.",
  "Your effort already shows, even if you can't see it yet.",
  "One gram at a time adds up too.",
  "Today you took one more step toward your goal.",
  "You're already doing it.",
  "Nobody handed you this; you're earning it.",
  "Every day logged is a quiet victory.",
  "Your consistency inspires more than you think.",
  "You're on the right track.",
  "The best is yet to come.",
  "If today was hard, tomorrow starts fresh.",
  "One stumble doesn't erase your path.",
  "It's okay not to have a perfect day.",
  "When you can't run, walk. But don't stop.",
  "Today is a day to be gentle with yourself.",
  "Bad days pass too.",
  "Don't give up on a bad day; rest and keep going.",
  "Starting again is brave too.",
  "You don't have to do it all; just don't drop it.",
  "Be your own cheerleader today.",
  "A day off isn't a failure.",
  "What matters is what you do after you slip.",
  "The road has curves, and that's okay.",
  "Don't punish yourself; adjust and keep going.",
  "Your worth doesn't depend on what you ate today.",
  "Tomorrow is a new page.",
  "Perfection doesn't exist; consistency does.",
  "You can start over as many times as you need.",
  "Even on slow days, you're still amazing.",
  "What matters is not letting go.",
  "Today is a great day to take care of yourself.",
  "Good morning, champ. Let's go for it all.",
  "Start the day with water and a good attitude.",
  "Make your first meal of the day a good decision.",
  "Today you're going to shine.",
  "Give your day the energy it deserves.",
  "Today's plan is simple: eat well and feel good.",
  "Smile, you look even better when you take care of yourself.",
  "You're in charge of your day.",
  "Make today count.",
  "Today your only competition is you.",
  "Get up with drive; your goal is waiting.",
  "Today is a good day to feel proud.",
  "Put on some music, move, smile.",
  "End the day knowing you gave your best.",
  "A good day starts with one good decision.",
  "Fill your day with things that are good for you.",
  "Your energy is contagious, use it well.",
  "Finish the day stronger than you started.",
  "You've got this today too.",
  "Today's consistency is tomorrow's confidence.",
  "Choose what brings you closer to your goal, even just a little.",
  "What you plant in your body, you harvest in your energy.",
  "Today there's no negotiating with yourself: you follow through.",
  "You're capable of big things, starting with the small ones.",
];

const FRASES_AMOR_EN = [
  "I love you in every version of you, and I love watching you grow.",
  "I'm proud of you, Glori. Today and always.",
  "You're the most beautiful part of my days, my love.",
  "Every time you take care of yourself, I fall more in love with you.",
  "Thank you for being my partner in everything, baby.",
  "You're already perfect to me; this is so you feel amazing too.",
  "You make me happy in ways I can't explain.",
  "Everything is better with you, Glorita.",
  "You're my favorite place.",
  "I admire you more than I tell you.",
  "Your smile fixes my whole day, Glori.",
  "I'll always be on your side.",
  "There's no goal you can't reach, and I'll be there to see it.",
  "I love the strong woman you are.",
  "You're my person.",
  "If today is hard, baby, remember that I believe in you.",
  "I'd choose you every single day.",
  "You're my motivation too.",
  "Your effort inspires me.",
  "How lucky I am to have you, amorchi.",
  "You're beautiful inside and out.",
  "I love being a team with you.",
  "You achieve everything you set your mind to, Glori. This too.",
  "I love you more than yesterday and less than tomorrow.",
  "Thank you for making my life more beautiful.",
  "Taking care of you is taking care of the person I love most.",
  "You're my peace, my love.",
  "I love seeing you happy, baby.",
  "You make any day special.",
  "Never forget how precious you are, Glorita.",
  "With you I want all the tomorrows.",
  "You're my pride and joy, baby.",
  "The number on the scale doesn't matter: I love you just the same.",
  "You're the best decision of my life.",
  "Your strength makes me fall in love, baby.",
  "I love everything about you, even what you don't see.",
  "I'm here for you, amorchi. Always.",
  "Together we can handle anything.",
  "You're my favorite adventure partner.",
  "Your wins are my joys.",
  "Every day with you is a gift.",
  "Your happiness is my priority.",
  "I love how your eyes light up when you achieve something.",
  "You're stronger than you think, and more loved than you imagine.",
  "My heart is yours, Glori.",
  "Thank you for your patience, your love and your laugh.",
  "You're the reason behind so many of my smiles.",
  "You're the best thing that ever happened to me.",
  "With you I learned what real love is.",
  "You can do it, baby, and I'm cheering for you from here.",
  "I'm thinking of you today too, my love.",
  "I wish you could see yourself through my eyes, Glorita.",
  "You're my home.",
  "I want you healthy, happy and with me for a long, long time.",
  "Your discipline makes me fall for you.",
  "You're incredible, Glorita. Don't forget it.",
  "It's so beautiful to grow by your side.",
  "Your effort doesn't go unnoticed by me.",
  "Thank you for letting me be with you on this.",
  "I love you for who you are, not for how you look.",
  "You're my sunshine on cloudy days.",
  "You make me want to be better every day.",
  "With you even the simple things are special.",
  "You're my favorite, Glori. Always.",
  "Your well-being is my joy.",
  "Together, taking care of each other and loving each other.",
  "I love our life together.",
  "You're my best friend and my love.",
  "You shine without even trying.",
  "You're doing something beautiful for yourself, and that makes me happy.",
  "I love you with everything I am, baby.",
  "It inspires me to see how you never give up.",
  "You're enough, you always have been.",
  "Time flies with you.",
  "Your laugh is my favorite sound, amorchi.",
  "You're my team.",
  "So proud to say you're mine, and I'm yours.",
  "Today I'm sending you a hug in the shape of a sentence, baby.",
  "Never stop believing in yourself; I never will.",
  "You're my home, wherever we are.",
  "I love the way you see life.",
  "You make me feel lucky every day.",
  "You make everything worth it.",
  "Thank you for existing, Glorita.",
  "You're my favorite inspiration.",
  "When I look at you, I know I chose right.",
  "I see you, I value you and I love you.",
  "You're my daily joy, my love.",
  "You'll always be my priority.",
  "Your heart is the most beautiful thing about you.",
  "I want to celebrate every goal with you.",
  "I love that you're taking care of yourself, my love. You deserve it.",
  "You're my best story.",
  "I love you today, tomorrow and every day, Glori.",
  "My admiration for you grows every day.",
  "You're strong, beautiful and mine.",
  "Nothing makes me happier than seeing you well, baby.",
  "You and me, always, amorchi.",
  "Thank you for making every day something special.",
  "I love you, Glori.",
];

const FRASES_VERSICULOS_EN = [
  ["I can do all things through Christ which strengtheneth me.", "Philippians 4:13"],
  ["Strength and honour are her clothing; and she shall rejoice in time to come.", "Proverbs 31:25"],
  ["God is in the midst of her; she shall not be moved.", "Psalm 46:5"],
  ["The LORD is my shepherd; I shall not want.", "Psalm 23:1"],
  ["But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.", "Matthew 6:33"],
  ["Commit thy way unto the LORD; trust also in him; and he shall bring it to pass.", "Psalm 37:5"],
  ["Delight thyself also in the LORD; and he shall give thee the desires of thine heart.", "Psalm 37:4"],
  ["This is the day which the LORD hath made; we will rejoice and be glad in it.", "Psalm 118:24"],
  ["Casting all your care upon him; for he careth for you.", "1 Peter 5:7"],
  ["Come unto me, all ye that labour and are heavy laden, and I will give you rest.", "Matthew 11:28"],
  ["Charity suffereth long, and is kind.", "1 Corinthians 13:4"],
  ["And now abideth faith, hope, charity, these three; but the greatest of these is charity.", "1 Corinthians 13:13"],
  ["Trust in the LORD with all thine heart; and lean not unto thine own understanding.", "Proverbs 3:5"],
  ["In all thy ways acknowledge him, and he shall direct thy paths.", "Proverbs 3:6"],
  ["Thy word is a lamp unto my feet, and a light unto my path.", "Psalm 119:105"],
  ["The LORD is my light and my salvation; whom shall I fear?", "Psalm 27:1"],
  ["Be still, and know that I am God.", "Psalm 46:10"],
  ["God is our refuge and strength, a very present help in trouble.", "Psalm 46:1"],
  ["Call unto me, and I will answer thee.", "Jeremiah 33:3"],
  ["For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.", "Jeremiah 29:11"],
  ["Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee.", "Isaiah 41:10"],
  ["But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles.", "Isaiah 40:31"],
  ["They shall run, and not be weary; and they shall walk, and not faint.", "Isaiah 40:31"],
  ["He giveth power to the faint; and to them that have no might he increaseth strength.", "Isaiah 40:29"],
  ["I will praise thee; for I am fearfully and wonderfully made.", "Psalm 139:14"],
  ["Thou art all fair, my love; there is no spot in thee.", "Song of Solomon 4:7"],
  ["I am my beloved's, and my beloved is mine.", "Song of Solomon 6:3"],
  ["Many waters cannot quench love, neither can the floods drown it.", "Song of Solomon 8:7"],
  ["Set me as a seal upon thine heart.", "Song of Solomon 8:6"],
  ["Two are better than one.", "Ecclesiastes 4:9"],
  ["A threefold cord is not quickly broken.", "Ecclesiastes 4:12"],
  ["To every thing there is a season, and a time to every purpose under the heaven.", "Ecclesiastes 3:1"],
  ["A merry heart maketh a cheerful countenance.", "Proverbs 15:13"],
  ["A merry heart doeth good like a medicine.", "Proverbs 17:22"],
  ["Keep thy heart with all diligence; for out of it are the issues of life.", "Proverbs 4:23"],
  ["Favour is deceitful, and beauty is vain: but a woman that feareth the LORD, she shall be praised.", "Proverbs 31:30"],
  ["Who can find a virtuous woman? for her price is far above rubies.", "Proverbs 31:10"],
  ["She girdeth her loins with strength, and strengtheneth her arms.", "Proverbs 31:17"],
  ["She openeth her mouth with wisdom; and in her tongue is the law of kindness.", "Proverbs 31:26"],
  ["Know ye not that your body is the temple of the Holy Ghost which is in you?", "1 Corinthians 6:19"],
  ["Therefore glorify God in your body, and in your spirit, which are God's.", "1 Corinthians 6:20"],
  ["Whether therefore ye eat, or drink, or whatsoever ye do, do all to the glory of God.", "1 Corinthians 10:31"],
  ["And whatsoever ye do, do it heartily, as to the Lord, and not unto men.", "Colossians 3:23"],
  ["And let us not be weary in well doing: for in due season we shall reap, if we faint not.", "Galatians 6:9"],
  ["But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, temperance.", "Galatians 5:22-23"],
  ["For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.", "2 Timothy 1:7"],
  ["He which hath begun a good work in you will perform it.", "Philippians 1:6"],
  ["Be careful for nothing.", "Philippians 4:6"],
  ["And the peace of God, which passeth all understanding, shall keep your hearts.", "Philippians 4:7"],
  ["Rejoice in the Lord alway: and again I say, Rejoice.", "Philippians 4:4"],
  ["I press toward the mark for the prize of the high calling of God in Christ Jesus.", "Philippians 3:14"],
  ["Forgetting those things which are behind, and reaching forth unto those things which are before.", "Philippians 3:13"],
  ["And we know that all things work together for good to them that love God.", "Romans 8:28"],
  ["If God be for us, who can be against us?", "Romans 8:31"],
  ["Rejoicing in hope; patient in tribulation; continuing instant in prayer.", "Romans 12:12"],
  ["Be not overcome of evil, but overcome evil with good.", "Romans 12:21"],
  ["Now the God of hope fill you with all joy and peace in believing.", "Romans 15:13"],
  ["The joy of the LORD is your strength.", "Nehemiah 8:10"],
  ["Be strong and of a good courage; be not afraid, neither be thou dismayed.", "Joshua 1:9"],
  ["The LORD bless thee, and keep thee.", "Numbers 6:24"],
  ["The LORD make his face shine upon thee, and be gracious unto thee.", "Numbers 6:25"],
  ["They are new every morning: great is thy faithfulness.", "Lamentations 3:23"],
  ["It is of the LORD's mercies that we are not consumed, because his compassions fail not.", "Lamentations 3:22"],
  ["Create in me a clean heart, O God; and renew a right spirit within me.", "Psalm 51:10"],
  ["Bless the LORD, O my soul, and forget not all his benefits.", "Psalm 103:2"],
  ["I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the LORD.", "Psalm 121:1-2"],
  ["The LORD shall preserve thy going out and thy coming in from this time forth, and even for evermore.", "Psalm 121:8"],
  ["I will both lay me down in peace, and sleep: for thou, LORD, only makest me dwell in safety.", "Psalm 4:8"],
  ["O taste and see that the LORD is good.", "Psalm 34:8"],
  ["The LORD is nigh unto them that are of a broken heart.", "Psalm 34:18"],
  ["He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.", "Psalm 91:1"],
  ["So teach us to number our days, that we may apply our hearts unto wisdom.", "Psalm 90:12"],
  ["And let the beauty of the LORD our God be upon us.", "Psalm 90:17"],
  ["He healeth the broken in heart, and bindeth up their wounds.", "Psalm 147:3"],
  ["Let every thing that hath breath praise the LORD. Praise ye the LORD.", "Psalm 150:6"],
  ["In thy presence is fulness of joy; at thy right hand there are pleasures for evermore.", "Psalm 16:11"],
  ["Weeping may endure for a night, but joy cometh in the morning.", "Psalm 30:5"],
  ["Cast thy burden upon the LORD, and he shall sustain thee.", "Psalm 55:22"],
  ["What time I am afraid, I will trust in thee.", "Psalm 56:3"],
  ["Beloved, I wish above all things that thou mayest prosper and be in health, even as thy soul prospereth.", "3 John 1:2"],
  ["There is no fear in love; but perfect love casteth out fear.", "1 John 4:18"],
  ["We love him, because he first loved us.", "1 John 4:19"],
  ["God is love.", "1 John 4:8"],
  ["Peace I leave with you, my peace I give unto you.", "John 14:27"],
  ["Let not your heart be troubled, neither let it be afraid.", "John 14:27"],
  ["For with God nothing shall be impossible.", "Luke 1:37"],
  ["Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.", "Matthew 7:7"],
  ["Ye are the light of the world.", "Matthew 5:14"],
  ["Take therefore no thought for the morrow.", "Matthew 6:34"],
  ["Lo, I am with you alway, even unto the end of the world.", "Matthew 28:20"],
  ["My grace is sufficient for thee: for my strength is made perfect in weakness.", "2 Corinthians 12:9"],
  ["If any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.", "2 Corinthians 5:17"],
  ["For we walk by faith, not by sight.", "2 Corinthians 5:7"],
  ["And above all these things put on charity, which is the bond of perfectness.", "Colossians 3:14"],
  ["Rejoice evermore. Pray without ceasing. In every thing give thanks.", "1 Thessalonians 5:16-18"],
  ["Arise, shine; for thy light is come.", "Isaiah 60:1"],
  ["Behold, I will do a new thing; now it shall spring forth.", "Isaiah 43:19"],
  ["The LORD shall fight for you, and ye shall hold your peace.", "Exodus 14:14"],
  ["The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love.", "Zephaniah 3:17"],
  ["Let us run with patience the race that is set before us.", "Hebrews 12:1"],
];
