/* ==========================================================
   Frases de la versión de Tiff — firmadas por NR.
   Edítalas libremente: una frase por línea, entre comillas.
   Cambian solas cada día (y no se repiten hasta dar la vuelta).
   ========================================================== */

const FRASES_MOTIVACION = [
  // constancia
  "No tiene que ser perfecto, tiene que ser constante.",
  "Un buen día no te cambia. Muchos días normales bien hechos, sí.",
  "La disciplina es acordarte de lo que quieres cuando no tienes ganas.",
  "Hoy solo te toca hacer lo de hoy.",
  "Pequeños pasos, todos los días. Así se llega lejos.",
  "No cuentes los días, haz que los días cuenten.",
  "Lo que haces seguido pesa más que lo que haces a veces.",
  "Si fallas una comida, la siguiente es tu nueva oportunidad.",
  "No se trata de empezar el lunes. Se trata de seguir hoy.",
  "Cada registro es un voto por la persona que quieres ser.",
  "Tu futuro se está construyendo con lo que decides hoy.",
  "Ir lento también es avanzar.",
  "Constancia le gana a intensidad, siempre.",
  "No necesitas motivación todos los días, necesitas hábitos.",
  "Lo difícil se vuelve normal si lo repites.",
  "Un día a la vez. Una comida a la vez.",
  "El progreso se esconde en los días aburridos.",
  "La meta no es un sprint, es un camino que disfrutas.",
  "Lo estás haciendo mejor de lo que crees.",
  "Mañana vas a agradecer lo que hiciste hoy.",
  "Cumplir contigo misma también es una forma de amor propio.",
  "El hábito que construyes hoy te sostiene mañana.",
  "No pares porque va lento. Para nada.",
  "Lo que no se mide no se mejora, y tú lo estás midiendo.",
  "Una mala comida no arruina un buen día.",
  "Un mal día no arruina una buena semana.",
  "Registrar lo que comes es darte información, no juzgarte.",
  "La constancia se construye con días imperfectos.",
  "No busques el día perfecto para empezar. Hoy es suficiente.",
  "Tu mejor versión no aparece de golpe, se entrena.",
  // comida
  "Come para nutrirte, no para castigarte.",
  "Tu plato de hoy es una inversión en tu energía de mañana.",
  "Proteína primero, lo demás se acomoda.",
  "El agua también es parte del plan.",
  "Comer bien es cuidarte, no hacer dieta.",
  "Ningún alimento es bueno o malo; es cuestión de cantidades.",
  "Pesar tu comida es darle a tu esfuerzo la precisión que merece.",
  "Las verduras nunca sobran en el plato.",
  "Comer despacio también es comer bien.",
  "Llena tu plato de colores.",
  "Planear tu comida es la mitad del trabajo.",
  "Un antojo no es una orden.",
  "Puedes disfrutar la comida y cuidar tu meta al mismo tiempo.",
  "Escoge lo que te hace sentir bien después, no solo durante.",
  "Tu cuerpo agradece la comida de verdad.",
  "Tener hambre de verdad y tener ganas de comer no son lo mismo.",
  "Balance no es perfección, es equilibrio.",
  "Deja espacio para lo que disfrutas; eso también es sostenible.",
  "Cocinar en casa es una forma de quererte.",
  "Cada comida es una nueva oportunidad de elegir bien.",
  "Nutrirte bien es el mejor regalo diario para tu cuerpo.",
  "Come con intención, no con distracción.",
  "Menos procesado, más real.",
  "La fruta también es postre.",
  "Hidrátate antes de decidir si tienes hambre.",
  "El desayuno de campeona no tiene que ser complicado.",
  "Un plato bien armado te deja satisfecha y con energía.",
  "La comida es combustible y también es placer. Las dos cosas caben.",
  "Tu meta de proteína te ayuda a sentirte llena y fuerte.",
  "Cuida las porciones, no te prohíbas nada.",
  // cuerpo y ejercicio
  "Muévete porque quieres a tu cuerpo, no porque lo odias.",
  "Una caminata también cuenta.",
  "Tu cuerpo puede más de lo que tu mente cree.",
  "Sudar hoy es sonreír mañana.",
  "El mejor ejercicio es el que sí vas a hacer.",
  "Diez minutos de movimiento le ganan a cero.",
  "Fuerte no es un tamaño, es una actitud.",
  "Cada repetición cuenta.",
  "El cansancio de entrenar se siente mejor que el arrepentimiento de no hacerlo.",
  "Estírate, respira, sigue.",
  "Tu cuerpo te escucha; háblale bonito.",
  "Entrena para sentirte bien, no solo para verte bien.",
  "Subir escaleras también es entrenar.",
  "No compitas con nadie más que con la de ayer.",
  "Hoy muévete un poco más que ayer.",
  "Tu cuerpo es tu casa; cuídalo como tal.",
  "Mover el cuerpo también limpia la mente.",
  "Aunque sea poquito, hazlo.",
  "Tus piernas pueden más. Tu mente también.",
  "El sudor es tu esfuerzo saliendo a saludar.",
  // descanso y bienestar
  "Dormir bien también es parte del progreso.",
  "Descansar no es rendirse, es recargar.",
  "Escucha a tu cuerpo: a veces pide movimiento, a veces pide pausa.",
  "El estrés también pesa; respira hondo.",
  "Tu salud mental importa tanto como tu meta.",
  "Un día de descanso también es parte del plan.",
  "Apaga la pantalla, duerme temprano, gana mañana.",
  "Tomar agua es el hábito más fácil de ganar hoy.",
  "Cuídate como cuidarías a alguien que amas.",
  "La paciencia también es una fortaleza.",
  "Respira. Lo estás haciendo bien.",
  "Tu energía de hoy depende de cómo dormiste anoche.",
  "Date permiso de descansar sin culpa.",
  "Un cuerpo descansado toma mejores decisiones.",
  "Bajar el ritmo no es retroceder.",
  // mentalidad
  "Cree en ti aunque la báscula no coopere hoy.",
  "La báscula mide peso, no tu valor.",
  "Tu progreso no siempre se ve en números.",
  "Compárate solo con la versión de ti de hace un mes.",
  "La motivación te arranca; el hábito te mantiene.",
  "Eres más fuerte que cualquier antojo.",
  "Háblate como le hablarías a tu mejor amiga.",
  "Tus metas merecen tu esfuerzo.",
  "Dudar es normal. Rendirse es opcional.",
  "Lo que hoy te cuesta, mañana te sale solo.",
  "El cambio empieza en la cabeza y termina en el espejo.",
  "No es suerte, es trabajo de todos los días.",
  "Tu actitud decide la mitad del resultado.",
  "Confía en el proceso, aunque no veas el final.",
  "Cada decisión cuenta, hasta las pequeñas.",
  "La versión de ti que quieres ser ya empezó a existir.",
  "No te enfoques en lo que falta, celebra lo que llevas.",
  "Tú puedes con días difíciles; ya lo has demostrado.",
  "Ser amable contigo también es parte del plan.",
  "El miedo a fallar no debe ganarle a tus ganas de intentarlo.",
  "Paso a paso, pero sin parar.",
  "Si fuera fácil, no sería tan bonito lograrlo.",
  "Tu esfuerzo de hoy es la sonrisa de mañana.",
  "No hace falta que alguien crea en ti si tú crees.",
  "Recuerda por qué empezaste.",
  "Una mente tranquila come mejor.",
  "La culpa no quema calorías; seguir adelante sí ayuda.",
  "Todo lo que vale la pena toma tiempo.",
  "Tú decides cómo termina el día.",
  "Tu cuerpo no es un proyecto; es tu compañero.",
  "Vas a lograrlo porque ya decidiste intentarlo.",
  "El progreso lento sigue siendo progreso.",
  "Que nadie apague tus ganas, ni siquiera tú.",
  "Enfócate en lo que puedes controlar hoy.",
  "Nadie ve tu esfuerzo diario, pero tu cuerpo sí lo nota.",
  "Una decisión saludable lleva a la siguiente.",
  "Sé paciente contigo; estás aprendiendo.",
  "Estás construyendo algo que dura.",
  "Hacer las cosas bien se siente bien.",
  "Los resultados llegan a quien no se detiene.",
  // progreso y logros
  "Mira hasta dónde has llegado.",
  "Cada semana registrada es una semana ganada.",
  "Celebra cada pequeño logro.",
  "Tu ropa, tu energía y tu ánimo también son resultados.",
  "Hoy eres más constante que ayer.",
  "Lo que antes era difícil hoy ya es costumbre.",
  "Tu racha es prueba de tu compromiso.",
  "Ya no estás empezando; estás avanzando.",
  "La meta está más cerca de lo que parece.",
  "Estás escribiendo tu propia historia de éxito.",
  "El progreso real es el que puedes sostener.",
  "Tu esfuerzo ya se nota, aunque tú todavía no lo veas.",
  "Un gramo a la vez también suma.",
  "Hoy diste un paso más hacia tu meta.",
  "Ya lo estás logrando.",
  "Nadie te regaló esto; te lo estás ganando.",
  "Cada día registrado es una victoria silenciosa.",
  "Tu constancia inspira más de lo que crees.",
  "Vas por buen camino.",
  "Lo mejor está por venir.",
  // días difíciles
  "Si hoy fue difícil, mañana empieza limpio.",
  "Un tropiezo no borra tu camino.",
  "Está bien no tener un día perfecto.",
  "Cuando no puedas correr, camina. Pero no te detengas.",
  "Hoy toca ser suave contigo.",
  "Los días malos también pasan.",
  "No te rindas en un mal día; descansa y sigue.",
  "Volver a empezar también es valiente.",
  "No hace falta hacerlo todo; basta con no dejarlo.",
  "Sé tu propia porra hoy.",
  "Un día libre no es un fracaso.",
  "Lo importante es lo que haces después de fallar.",
  "El camino tiene curvas, y está bien.",
  "No te castigues; ajusta y sigue.",
  "Tu valor no depende de lo que comiste hoy.",
  "Mañana es otra página.",
  "La perfección no existe; la constancia sí.",
  "Puedes empezar de nuevo las veces que haga falta.",
  "Incluso en los días lentos, sigues siendo increíble.",
  "Lo que importa es no soltar.",
  // energía del día
  "Hoy es un gran día para cuidarte.",
  "Buenos días, campeona. Vamos por todo.",
  "Arranca el día con agua y buena actitud.",
  "Que tu primera comida del día sea una buena decisión.",
  "Hoy vas a brillar.",
  "Dale a tu día la energía que mereces.",
  "Hoy el plan es sencillo: comer bien y sentirte bien.",
  "Sonríe, te ves mejor cuando te cuidas.",
  "Tú mandas en tu día.",
  "Haz que hoy cuente.",
  "Hoy tu única competencia eres tú.",
  "Levántate con ganas; la meta te espera.",
  "Hoy es un buen día para sentirte orgullosa.",
  "Pon música, muévete, sonríe.",
  "Cierra el día sabiendo que diste lo mejor.",
  "Un buen día empieza con una buena decisión.",
  "Llena tu día de cosas que te hagan bien.",
  "Tu energía es contagiosa, úsala bien.",
  "Termina el día más fuerte de lo que empezaste.",
  "Hoy también vas a poder.",
  "Tu constancia de hoy es tu confianza de mañana.",
  "Elige lo que te acerca a tu meta, aunque sea poquito.",
  "Lo que siembras en tu cuerpo, lo cosechas en tu energía.",
  "Hoy no se negocia contigo misma: se cumple.",
  "Eres capaz de cosas grandes, empezando por las pequeñas.",
];

const FRASES_AMOR = [
  "Te amo en todas tus versiones, y me encanta verte crecer.",
  "Estoy orgulloso de ti, Glori. Hoy y siempre.",
  "Eres lo más bonito de mis días, amorcito.",
  "Cada vez que te cuidas, me enamoro más de ti.",
  "Gracias por ser mi compañera en todo, baby.",
  "Ya eres perfecta para mí; esto es para que te sientas increíble tú.",
  "Me haces feliz de maneras que no sé explicar.",
  "Contigo todo es mejor, Glorita.",
  "Eres mi lugar favorito.",
  "Te admiro más de lo que te digo.",
  "Tu sonrisa me arregla el día, Glori.",
  "Siempre voy a estar de tu lado.",
  "No hay meta que no puedas lograr, y yo voy a estar ahí para verlo.",
  "Me encanta la mujer fuerte que eres.",
  "Eres mi persona.",
  "Si hoy te cuesta, bebé, recuerda que yo creo en ti.",
  "Te elegiría todos los días.",
  "Eres mi motivación también.",
  "Tu esfuerzo me inspira.",
  "Qué suerte tengo de tenerte, amorchi.",
  "Eres hermosa por dentro y por fuera.",
  "Me encanta hacer equipo contigo.",
  "Todo lo que te propones lo logras, Glori. Esto también.",
  "Te amo más que ayer y menos que mañana.",
  "Gracias por hacer mi vida más bonita.",
  "Cuidarte es cuidar a la persona que más amo.",
  "Eres mi paz, amorcito.",
  "Me encanta verte feliz, baby.",
  "Tú haces que cualquier día sea especial.",
  "Nunca olvides lo valiosa que eres, Glorita.",
  "Contigo quiero todos los mañanas.",
  "Eres mi orgullo, baby.",
  "No importa el número de la báscula: te amo igual.",
  "Eres la mejor decisión de mi vida.",
  "Tu fuerza me enamora, bebé.",
  "Me gusta todo de ti, hasta lo que tú no ves.",
  "Estoy aquí para ti, amorchi. Siempre.",
  "Juntos podemos con todo.",
  "Eres mi compañera favorita de aventuras.",
  "Tus logros son mis alegrías.",
  "Cada día contigo es un regalo.",
  "Tu felicidad es mi prioridad.",
  "Me encanta cómo te brillan los ojos cuando logras algo.",
  "Eres más fuerte de lo que crees, y más amada de lo que imaginas.",
  "Mi corazón es tuyo, Glori.",
  "Gracias por tu paciencia, tu amor y tu risa.",
  "Eres la razón de muchas de mis sonrisas.",
  "Eres lo mejor que me ha pasado.",
  "Contigo aprendí lo que es querer de verdad.",
  "Tú puedes, baby, y yo te echo porras desde aquí.",
  "Hoy también pienso en ti, amorcito.",
  "Ojalá te vieras con mis ojos, Glorita.",
  "Eres mi casa.",
  "Te quiero sana, feliz y conmigo mucho tiempo.",
  "Me enamora tu disciplina.",
  "Eres increíble, Glorita. No lo olvides.",
  "Qué bonito es crecer a tu lado.",
  "Tu esfuerzo no pasa desapercibido para mí.",
  "Gracias por dejarme acompañarte en esto.",
  "Te amo por quien eres, no por cómo te ves.",
  "Eres mi sol en los días nublados.",
  "Me haces querer ser mejor cada día.",
  "Contigo hasta lo simple es especial.",
  "Eres mi favorita, Glori. Siempre.",
  "Tu bienestar es mi alegría.",
  "Juntos, a cuidarnos y a querernos.",
  "Me encanta nuestra vida juntos.",
  "Eres mi mejor amiga y mi amor.",
  "Brillas sin intentarlo.",
  "Estás haciendo algo bonito por ti, y eso me hace feliz.",
  "Te amo con todo lo que soy, bebé.",
  "Me inspira ver cómo nunca te rindes.",
  "Eres suficiente, siempre lo has sido.",
  "Contigo el tiempo vuela.",
  "Tu risa es mi sonido favorito, amorchi.",
  "Eres mi equipo.",
  "Qué orgullo decir que eres mía, y yo tuyo.",
  "Hoy te mando un abrazo en forma de frase, baby.",
  "Nunca dejes de creer en ti; yo nunca lo haré.",
  "Eres mi hogar, donde sea que estemos.",
  "Me encanta tu forma de ver la vida.",
  "Me haces sentir afortunado todos los días.",
  "Tú haces que todo valga la pena.",
  "Gracias por existir, Glorita.",
  "Eres mi inspiración favorita.",
  "Cuando te miro, sé que elegí bien.",
  "Te veo, te valoro y te amo.",
  "Eres mi alegría diaria, amorcito.",
  "Siempre serás mi prioridad.",
  "Tu corazón es lo más bonito que tienes.",
  "Contigo quiero celebrar cada meta.",
  "Me encanta que te estés cuidando, amorcito. Te lo mereces.",
  "Eres mi mejor historia.",
  "Te amo hoy, mañana y todos los días, Glori.",
  "Mi admiración por ti crece cada día.",
  "Eres fuerte, bella y mía.",
  "Nada me hace más feliz que verte bien, bebé.",
  "Tú y yo, siempre, amorchi.",
  "Gracias por hacer de cada día algo especial.",
  "Te amo, Glori.",
];
